name: lancamento_contatos
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.2        # Ícones Default
  google_fonts: ^3.0.1           # Fonte customizada
  flutter_platform_alert: ^0.3.0 # Alert específico de cada plataforma
  date_field: ^3.0.0             # Campo de Data/Hora
  drop_down_list: ^0.0.4         # Campo Combobox
  brasil_fields: ^1.9.0          # Mascaras e Formatos Brasileiros
  modal_bottom_sheet: ^2.1.2     # Bottom Sheet

  # Util
  localization: ^2.1.0           # Localizações PT-BR
  intl: ^0.17.0                  # Formatações (can`t upgrade)
  uuid: ^3.0.7                   # Id único
  pdf: ^3.8.4                    # Criação do PDF de relatórios
  share_plus: ^6.3.0             # Compartilhar Arquivos
  path_provider: ^2.0.11         # Caminhos do App

  # Database
  hive: ^2.2.3                   # Banco de dados local
  hive_flutter: ^1.1.0           # Banco de dados local
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0           # Boas práticas no Flutter
  hive_generator: ^2.0.0          # Gerador de adapter para Hive
  build_runner: ^2.3.3            # Comandos autmatizados
  change_app_package_name: ^1.1.0 # Alterar package do app facilmente
  flutter_launcher_icons: ^0.11.0 # Ícones do appß

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo-app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/